# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'EFLASH' do
    project 'EZOEF.xcodeproj'
    use_frameworks!
    
    pod 'Alamofire', '4.9.1'
    pod 'KYDrawerController'
    pod 'SwiftyJSON'
    pod 'CryptoSwift', '1.3.0'
    pod 'GradientCircularProgress', :git => 'https://github.com/keygx/GradientCircularProgress'
    pod 'Locksmith'
    pod 'Countly'

    
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        end
      end
    end
end
