# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 4da3262c-6b02-4c4b-9aaa-2fa9e693eb8b
langcode: nl
status: true
dependencies:
  module:
    - system
  theme:
    - ezoef
_core:
  default_config_hash: QjdwDFua2xY5rANgnDkpI3Th1Z_ba8Dtyp_Cx0qiSwU
id: ezoef_content
theme: ezoef
region: content
weight: 0
provider: null
plugin: system_main_block
settings:
  id: system_main_block
  label: 'Main page content'
  provider: system
  label_display: '0'
visibility: {  }
