# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 18177a3c-9cdf-4525-8926-b5ad9d21a2e5
langcode: nl
status: true
dependencies:
  theme:
    - seven
_core:
  default_config_hash: c-06bbElRY5sKmglk74ppgTW93Et4-EJFyNiUZMb8JY
id: seven_local_tasks
theme: seven
region: content
weight: -4
provider: null
plugin: local_tasks_block
settings:
  id: local_tasks_block
  label: Tabbladen
  provider: core
  label_display: '0'
  primary: true
  secondary: true
visibility: {  }
