# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 6f4b562d-5a63-47f9-a8e6-487ca52c98b8
langcode: nl
status: true
dependencies:
  module:
    - system
  theme:
    - seven
_core:
  default_config_hash: 5MNdk3fpMKx_xxBTcz2T11DL4XEU1H5SgHl8BsYdFsA
id: seven_messages
theme: seven
region: highlighted
weight: 0
provider: null
plugin: system_messages_block
settings:
  id: system_messages_block
  label: Statusberichten
  provider: system
  label_display: '0'
visibility: {  }
