# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: aa098217-9393-44bf-a021-a0ae1e355015
langcode: nl
status: false
dependencies:
  config:
    - system.menu.tools
  module:
    - system
  theme:
    - seven
_core:
  default_config_hash: xCOijLdB1-UgXxQ9a0D1_pd8vxNEhfMnxXZc8jYhHjs
id: seven_tools
theme: seven
region: header
weight: -3
provider: null
plugin: 'system_menu_block:tools'
settings:
  id: 'system_menu_block:tools'
  label: Hulpmiddelen
  provider: system
  label_display: visible
  level: 1
  depth: 0
  expand_all_items: false
visibility: {  }
