# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 9c7f98c0-edcd-4a75-9fc3-9bc5a5b797f4
langcode: nl
status: true
dependencies: {  }
id: test_configuration
label: 'Test configuration'
description: ''
folder: ../config/test
module:
  devel: 0
theme: {  }
blacklist:
  - push_notifications.apns
  - push_notifications.apns.flash
  - push_notifications.apns.zoef
  - push_notifications.gcm
  - push_notifications.gcm.flash
  - push_notifications.gcm.zoef
  - syslog.settings
graylist: {  }
graylist_dependents: true
graylist_skip_equal: true
weight: 0
