# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: d7e8ab12-8066-4bca-aec3-157f657638ac
langcode: nl
status: true
dependencies: {  }
_core:
  default_config_hash: og8sWXhBuHbLMw3CoiBEZjgqSyhFBFmcbUW_wLcfNbo
id: long
label: 'Standaarddatum - lang'
locked: false
pattern: 'l, F j, Y - H:i'
