# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 385186df-fe0b-4637-a3b6-d05d4d03467c
langcode: nl
status: true
dependencies:
  config:
    - field.field.user.user.field_push_announcements
    - field.field.user.user.field_push_device_id
    - field.field.user.user.field_push_device_type
    - field.field.user.user.field_push_enabled
    - field.field.user.user.field_push_messagetypes
    - field.field.user.user.field_push_updates
    - field.field.user.user.field_registered_email_address
  module:
    - field_group
    - pcr
    - user
third_party_settings:
  field_group:
    group_push_settings:
      children:
        - field_push_enabled
        - field_push_updates
        - field_push_device_type
        - field_push_device_id
        - field_push_announcements
        - field_push_messagetypes
      parent_name: ''
      weight: 2
      format_type: tab
      region: content
      format_settings:
        id: ''
        classes: ''
        description: ''
        formatter: closed
        required_fields: true
      label: 'Push settings'
id: user.user.default
targetEntityType: user
bundle: user
mode: default
content:
  account:
    weight: 0
    region: content
    settings: {  }
    third_party_settings: {  }
  field_push_announcements:
    type: options_pretty
    weight: 10
    region: content
    settings: {  }
    third_party_settings: {  }
  field_push_device_id:
    type: string_textfield
    weight: 9
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_push_device_type:
    type: options_select
    weight: 8
    region: content
    settings: {  }
    third_party_settings: {  }
  field_push_enabled:
    type: options_pretty
    weight: 6
    region: content
    settings: {  }
    third_party_settings: {  }
  field_push_messagetypes:
    type: options_select
    weight: 11
    region: content
    settings: {  }
    third_party_settings: {  }
  field_push_updates:
    type: options_pretty
    weight: 7
    region: content
    settings: {  }
    third_party_settings: {  }
  field_registered_email_address:
    type: email_default
    weight: 1
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
hidden:
  langcode: true
  language: true
  timezone: true
