# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: b51ec91d-c25e-4ed8-8068-c40745bb3867
langcode: nl
status: true
dependencies:
  config:
    - taxonomy.vocabulary.app_domains
id: taxonomy_term.app_domains.default
targetEntityType: taxonomy_term
bundle: app_domains
mode: default
content: {  }
hidden:
  description: true
  langcode: true
