# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 5a0a85a5-67a3-4319-bd22-176a2c66ea8f
langcode: nl
status: true
dependencies: {  }
_core:
  default_config_hash: nzL5d024NjXIX_8TlT6uFAu973lmfkmHklJC-2i9rAE
id: medium
label: 'Standaarddatum - middel'
locked: false
pattern: 'D, m/d/Y - H:i'
