# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 7b60df9e-7d19-485b-827c-e81aa05d5342
langcode: nl
status: true
dependencies:
  config:
    - comment.type.berichten_updates
    - field.field.comment.berichten_updates.comment_body
  module:
    - text
id: comment.berichten_updates.default
targetEntityType: comment
bundle: berichten_updates
mode: default
content:
  comment_body:
    type: text_textarea
    weight: 11
    settings:
      rows: 5
      placeholder: ''
    third_party_settings: {  }
    region: content
hidden:
  author: true
  langcode: true
  subject: true
