# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 0fc72fa7-311b-4058-8f2d-c03a74c231e3
langcode: nl
status: true
dependencies:
  config:
    - node.type.page
id: node.page.promote
field_name: promote
entity_type: node
bundle: page
label: 'Aangeraden op de voorpagina'
description: ''
required: false
translatable: true
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: Aan
  off_label: Uit
field_type: boolean
