# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: d365ec76-3647-4fef-9b53-4493c216389c
langcode: nl
status: true
dependencies:
  config:
    - field.field.node.announcement.body
    - field.field.node.announcement.field_berichttype
    - field.field.node.announcement.field_status
    - field.field.node.announcement.field_update
    - node.type.announcement
  module:
    - comment
    - shs
    - text
id: node.announcement.default
targetEntityType: node
bundle: announcement
mode: default
content:
  body:
    weight: 1
    settings:
      rows: 9
      summary_rows: 3
      placeholder: ''
      show_summary: false
    third_party_settings: {  }
    type: text_textarea_with_summary
    region: content
  created:
    type: datetime_timestamp
    weight: 6
    region: content
    settings: {  }
    third_party_settings: {  }
  field_berichttype:
    weight: 3
    settings:
      display_node_count: false
      create_new_items: false
      create_new_levels: false
      force_deepest: false
    third_party_settings: {  }
    type: options_shs
    region: content
  field_status:
    weight: 2
    settings: {  }
    third_party_settings: {  }
    type: options_select
    region: content
  field_update:
    weight: 4
    settings: {  }
    third_party_settings: {  }
    type: comment_default
    region: content
  title:
    type: string_textfield
    weight: 0
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  uid:
    type: entity_reference_autocomplete
    weight: 5
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
      match_limit: 10
    region: content
    third_party_settings: {  }
hidden:
  langcode: true
  path: true
  promote: true
  status: true
  sticky: true
