# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: f93d3cd8-58f3-4e77-a065-34124e426fca
langcode: nl
status: true
dependencies:
  config:
    - filter.format.wysiwyg_default
  module:
    - ckeditor
format: wysiwyg_default
editor: ckeditor
settings:
  toolbar:
    rows:
      -
        -
          name: Formatting
          items:
            - Bold
            - Italic
        -
          name: Lists
          items:
            - BulletedList
        -
          name: Templates
          items:
            - TemplateSelector
  plugins:
    stylescombo:
      styles: ''
    language:
      language_list: un
image_upload:
  status: false
  scheme: public
  directory: inline-images
  max_size: ''
  max_dimensions:
    width: null
    height: null
