# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
brand_color: orange
sender_primary: 'Ministerie van Economische Zaken en Klimaat'
sender_secondary: ''
sender_breakpoint: ''
titlebar: ''
header_bg_picture: {  }
header_bg_picture_width: '6'
header_bg_color: '1'
navigation_border: 1
langcode: nl
