# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 8d3d129e-18e7-434f-9152-24a8c2673c97
langcode: nl
status: true
dependencies:
  config:
    - field.storage.user.field_push_device_id
  module:
    - user
id: user.user.field_push_device_id
field_name: field_push_device_id
entity_type: user
bundle: user
label: 'Push device id'
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
