# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: d3cea42f-0dcc-4205-aa2a-e636d89c40fa
langcode: nl
status: true
dependencies:
  module:
    - node
    - options
id: node.field_status
field_name: field_status
entity_type: node
type: list_string
settings:
  allowed_values:
    -
      value: open
      label: Open
    -
      value: closed
      label: Closed
    -
      value: archived
      label: Archived
  allowed_values_function: ''
module: options
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
