# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 3556f869-f8c6-4bb3-a6cd-e955c652a088
langcode: nl
status: true
dependencies:
  config:
    - field.storage.user.field_push_enabled
  module:
    - user
id: user.user.field_push_enabled
field_name: field_push_enabled
entity_type: user
bundle: user
label: 'Push enabled'
description: ''
required: false
translatable: false
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: Aan
  off_label: Uit
field_type: boolean
