# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: ce05db6b-0bb5-490a-81b5-e7a424983c82
langcode: nl
status: true
dependencies:
  module:
    - user
id: user.field_push_enabled
field_name: field_push_enabled
entity_type: user
type: boolean
settings: {  }
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
