# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 11712578-143c-4e95-a4f0-4605c02d16d9
langcode: nl
status: true
dependencies:
  config:
    - field.storage.node.field_berichttype
    - node.type.incident
    - taxonomy.vocabulary.berichttypen
id: node.incident.field_berichttype
field_name: field_berichttype
entity_type: node
bundle: incident
label: Meldingstype
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      berichttypen: berichttypen
    sort:
      field: _none
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
