# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 87c85c7e-53d3-4f06-a6a6-38ac10d55fa5
langcode: nl
status: true
dependencies:
  config:
    - field.storage.user.field_push_announcements
  module:
    - user
id: user.user.field_push_announcements
field_name: field_push_announcements
entity_type: user
bundle: user
label: 'Push announcements'
description: ''
required: false
translatable: false
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: Aan
  off_label: Uit
field_type: boolean
