# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 5a24ec2e-5346-4b6a-b812-8a7c8605402d
langcode: nl
status: true
dependencies:
  module:
    - user
id: user.field_push_announcements
field_name: field_push_announcements
entity_type: user
type: boolean
settings: {  }
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
