# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 95c5735c-199c-4c5e-8f56-6855204617e3
langcode: nl
status: true
dependencies:
  config:
    - field.storage.node.field_status
    - node.type.incident
  module:
    - options
id: node.incident.field_status
field_name: field_status
entity_type: node
bundle: incident
label: Status
description: ''
required: true
translatable: false
default_value:
  -
    value: open
default_value_callback: ''
settings: {  }
field_type: list_string
