# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 425759ef-ef7f-4d53-8360-9834f3f5b163
langcode: nl
status: true
dependencies:
  module:
    - node
    - taxonomy
id: node.field_berichttype
field_name: field_berichttype
entity_type: node
type: entity_reference
settings:
  target_type: taxonomy_term
module: core
locked: false
cardinality: -1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
