# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 821aa646-4dc2-440b-9882-a874c379d0d6
langcode: nl
status: true
dependencies:
  config:
    - field.storage.node.field_update
    - node.type.announcement
  module:
    - comment
id: node.announcement.field_update
field_name: field_update
entity_type: node
bundle: announcement
label: Updates
description: ''
required: false
translatable: true
default_value:
  -
    status: 2
    cid: 0
    last_comment_timestamp: 0
    last_comment_name: null
    last_comment_uid: 0
    comment_count: 0
default_value_callback: ''
settings:
  default_mode: 0
  per_page: 50
  anonymous: 0
  form_location: true
  preview: 0
field_type: comment
