# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 9f56d5d2-f586-4b07-9e20-7eb620c25338
langcode: nl
status: true
dependencies:
  config:
    - field.storage.node.body
    - node.type.page
  module:
    - text
id: node.page.body
field_name: body
entity_type: node
bundle: page
label: Body
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  display_summary: true
  required_summary: false
field_type: text_with_summary
