# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: d0806f15-3bc0-4289-ad95-57b44dd3a6a3
langcode: nl
status: true
dependencies:
  config:
    - field.storage.node.body
    - node.type.announcement
  module:
    - text
id: node.announcement.body
field_name: body
entity_type: node
bundle: announcement
label: Omschrijving
description: ''
required: true
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  display_summary: false
  required_summary: false
field_type: text_with_summary
