# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: b4c4cd43-0906-472c-8e10-a8737c1a663d
langcode: nl
status: true
dependencies:
  config:
    - field.storage.user.field_push_device_type
  module:
    - options
    - user
id: user.user.field_push_device_type
field_name: field_push_device_type
entity_type: user
bundle: user
label: 'Push device type'
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: list_string
