# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

description:
  type: textfield
  length: 128
icon:
  directory: core/modules/file/icons
_core:
  default_config_hash: 8LI-1XgwLt9hYRns_7c81S632d6JhdqXKs4vDheaG6E
langcode: nl
make_unused_managed_files_temporary: false
