# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: cbd93f38-bdc7-47de-80ba-ef2eb3924549
langcode: nl
status: true
dependencies:
  module:
    - editor
_core:
  default_config_hash: NIKBt6kw_uPhNI0qtR2DnRf7mSOgAQdx7Q94SKMjXbQ
name: 'Platte text'
format: plain_text
weight: -9
filters:
  filter_html_escape:
    id: filter_html_escape
    provider: filter
    status: false
    weight: -49
    settings: {  }
  filter_url:
    id: filter_url
    provider: filter
    status: false
    weight: -48
    settings:
      filter_url_length: 72
  filter_autop:
    id: filter_autop
    provider: filter
    status: false
    weight: -50
    settings: {  }
  editor_file_reference:
    id: editor_file_reference
    provider: editor
    status: false
    weight: -44
    settings: {  }
  filter_htmlcorrector:
    id: filter_htmlcorrector
    provider: filter
    status: false
    weight: -46
    settings: {  }
  filter_align:
    id: filter_align
    provider: filter
    status: false
    weight: -43
    settings: {  }
  filter_caption:
    id: filter_caption
    provider: filter
    status: false
    weight: -42
    settings: {  }
  filter_html_image_secure:
    id: filter_html_image_secure
    provider: filter
    status: false
    weight: -41
    settings: {  }
  filter_html:
    id: filter_html
    provider: filter
    status: false
    weight: -45
    settings:
      allowed_html: '<a href hreflang> <em> <strong> <cite> <blockquote cite> <code> <ul type> <ol start type> <li> <dl> <dt> <dd> <h2 id> <h3 id> <h4 id> <h5 id> <h6 id>'
      filter_html_help: true
      filter_html_nofollow: false
