# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 6a3c2742-6fa6-4d3d-b51c-a167fc53954f
langcode: nl
status: true
dependencies: {  }
id: nl
label: Dutch
direction: ltr
weight: 0
locked: false
