# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 38f8582e-58f7-4c69-be7a-0e9b5f88c0d0
langcode: nl
status: true
dependencies:
  config:
    - node.type.page
id: node.page
target_entity_type_id: node
target_bundle: page
default_langcode: site_default
language_alterable: false
