# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 8bd6c8f4-b48a-46ce-95a0-0fe166c93d03
langcode: nl
status: true
dependencies: {  }
_core:
  default_config_hash: eNX6lLCKDaY83nCMh20My---y03KbiFlv802DKCCpvg
id: und
label: 'Niet gespecificeerd'
direction: ltr
weight: 2
locked: true
