# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

push_notifications: null
_core:
  default_config_hash: lurwzLD7ki9zpVwLhqB_VIVhYu15n1SCWeNEjUav_7c
langcode: nl
