# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

client_key: ''
environment: ''
release: 2.14.0
fatal_error_handler: true
fatal_error_handler_memory: 2560
log_levels:
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 0
  7: 0
  8: 0
stack: true
timeout: !!float 2
message_limit: 2048
trace: false
javascript_error_handler: false
public_dsn: ''
ssl: verify_ssl
ca_cert: ''
ignored_channels: {  }
_core:
  default_config_hash: kVe8NwytqsDxcxJh7huADkoR1szqSxKV2KKXnkMAEWw
langcode: nl
