# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 81376909-7643-46bf-ab9f-7a47b82f9ddb
langcode: nl
status: true
dependencies:
  module:
    - hal
    - nicol_api
    - serialization
    - simple_oauth
_core:
  default_config_hash: 0niFPKaxi0tk8qgL83XcD-Ociy96L2aSE9QfRvBUqFY
id: nicol_incidents
plugin_id: nicol_incidents
granularity: resource
configuration:
  methods:
    - POST
  formats:
    - hal_json
    - json
  authentication:
    - token_bearer
