# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 2fdd7e69-894e-49c5-a3cb-23995ce8a6b2
langcode: nl
status: true
dependencies:
  module:
    - hal
    - nicol_api
    - serialization
    - simple_oauth
_core:
  default_config_hash: GRu-QshckiFVe5nSzu-62AEMRx6fxTIB-COYWCDMXR4
id: nicol_push_notifications
plugin_id: nicol_push_notifications
granularity: resource
configuration:
  methods:
    - POST
    - DELETE
  formats:
    - hal_json
    - json
  authentication:
    - token_bearer
