# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: d9cdec75-97b8-463a-a333-b3b466849731
langcode: nl
status: true
dependencies:
  module:
    - hal
    - nicol_api
    - serialization
    - simple_oauth
_core:
  default_config_hash: rG2alAo3uuvmvOC4UNDzW1RwEMSXPbRyAxQe1wujFNs
id: nicol_messagetypes
plugin_id: nicol_messagetypes
granularity: resource
configuration:
  methods:
    - GET
  formats:
    - hal_json
    - json
  authentication:
    - token_bearer
