# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 9acf3325-517d-4a9f-a9e5-19a063771f34
langcode: nl
status: true
dependencies: {  }
_core:
  default_config_hash: U5VlGjd_SfV0Qm_EfnaynOfc549cNscFAx48JfYoMRI
id: default
label: Default
