# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

count_content_views: 0
display_max_age: 3600
_core:
  default_config_hash: mv_zxeyh1fioueMzVN4UxTYQqbcwJtWNATAqwGZRHwk
langcode: nl
