# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 70d59aed-f559-4d27-a190-1642b112e0a0
langcode: nl
status: true
dependencies:
  module:
    - node
_core:
  default_config_hash: Zx0jD1Klh5tZaGJy8uOeR_2MCu9FDM4xg7TaUJUEbkI
id: node_delete_action
label: 'Inhoud verwijderen'
type: node
plugin: 'entity:delete_action:node'
configuration: {  }
