# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: aca9ba6c-9932-413b-9b0a-71a17369570d
langcode: nl
status: true
dependencies:
  config:
    - user.role.servicedesk
  module:
    - user
id: user_remove_role_action.servicedesk
label: 'Verwijder de rol Servicedesk van de geselecteerde gebruikers'
type: user
plugin: user_remove_role_action
configuration:
  rid: servicedesk
