# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: fe85afb1-4359-457c-b8fa-da755183d93e
langcode: nl
status: true
dependencies:
  module:
    - node
_core:
  default_config_hash: gGQXiSspwGl0lyOS6w_HCPpvGAPDciqDNLFwWOydVtI
id: node_unpublish_action
label: 'Publicatie ongedaan maken'
type: node
plugin: 'entity:unpublish_action:node'
configuration: {  }
