# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 1bd0f4f9-a9ec-4dbe-8c19-319aa4025240
langcode: nl
status: true
dependencies:
  module:
    - node
_core:
  default_config_hash: N0RDBTqiK4dKoN4p4oW2j0SGWycdHyALUe9M-Ofp89U
id: node_promote_action
label: 'Inhoud op de voorpagina zichtbaar maken'
type: node
plugin: node_promote_action
configuration: {  }
