# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: f1052c2e-ddca-40fd-91d0-4c578154c030
name: 'eZoef en eFlash beheer'
mail: no-reply@dictu.nl
slogan: ''
page:
  403: ''
  404: ''
  front: /node/125
admin_compact_mode: false
weight_select_max: 100
langcode: nl
default_langcode: nl
_core:
  default_config_hash: AyT9s8OUcclfALRE_imByOMgtZ19eOlqdF6zI3p7yqo
mail_notification: ''
