# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: ebfba35d-a2ac-4d98-a04b-3c27dde5630d
langcode: nl
status: true
dependencies:
  module:
    - node
_core:
  default_config_hash: JBptjnfuOMtsdKygklXxoOgeOCTMtQxlkymjnnj-cC0
id: node_unpromote_action
label: 'Inhoud van de voorpagina verwijderen'
type: node
plugin: node_unpromote_action
configuration: {  }
