# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: cffd5647-3a8c-4675-b7cf-489e579a896b
langcode: nl
status: true
dependencies:
  config:
    - user.role.ezoef_app_user
  module:
    - user
id: user_add_role_action.ezoef_app_user
label: 'Voeg de rol ezoef app user toe aan de geselecteerde gebruikers'
type: user
plugin: user_add_role_action
configuration:
  rid: ezoef_app_user
