# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

threshold:
  requirements_warning: 172800
  requirements_error: 1209600
_core:
  default_config_hash: 05U0n1_8zHYzxEFSWjyHCWuJyhdez2a6Z_aTIXin04E
langcode: nl
logging: 0
