# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 186ab515-8c78-4e6f-8445-8fa37dcd5a56
langcode: nl
status: true
dependencies:
  module:
    - user
_core:
  default_config_hash: SPsUXsR3Rc8d1y3gewzaAKWa1ncea_ywXX3f7LTn7k0
id: user_unblock_user_action
label: 'De geselecteerde gebruiker(s) activeren'
type: user
plugin: user_unblock_user_action
configuration: {  }
