# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 56ad1d42-a209-4d58-9c78-ffb95653f75e
langcode: nl
status: true
dependencies:
  module:
    - user
_core:
  default_config_hash: DyypzTfThX10FFQw-399qPfEbLLyrhXgQrKPVsmAoJ4
id: user_block_user_action
label: 'De geselecteerde gebruiker(s) blokkeren'
type: user
plugin: user_block_user_action
configuration: {  }
