# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

allow_insecure_uploads: false
default_scheme: public
path: {  }
temporary_maximum_age: 21600
_core:
  default_config_hash: t48gCU9DzYfjb3bAOIqHLzhL0ChBlXh6_5B5Pyo9t8g
langcode: nl
