# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: dd5d8eec-d8aa-431d-8c97-6804833826fa
langcode: nl
status: true
dependencies:
  config:
    - user.role.ezflash_app_user
  module:
    - user
id: user_add_role_action.ezflash_app_user
label: 'Voeg de rol ezflash app user toe aan de geselecteerde gebruikers'
type: user
plugin: user_add_role_action
configuration:
  rid: ezflash_app_user
