# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: cd185968-6803-44bf-8cbc-ed3d4ab75857
langcode: nl
status: true
dependencies: {  }
name: Berichttypen
vid: berichttypen
description: 'berichtenstromen met daaronder berichttypen'
weight: 0
