# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 96f8a46f-8fda-41a9-bf1b-7416a2492aa0
langcode: nl
status: true
dependencies: {  }
id: administrator
label: Administrator
weight: 2
is_admin: true
permissions:
  - 'access administration pages'
  - 'access comments'
  - 'access content overview'
  - 'access contextual links'
  - 'access devel information'
  - 'access files overview'
  - 'access in-place editing'
  - 'access kint'
  - 'access rules debug'
  - 'access shortcuts'
  - 'access site in maintenance mode'
  - 'access site reports'
  - 'access toolbar'
  - 'access user profiles'
  - 'add access token entities'
  - 'add push notification'
  - 'add simple_oauth entities'
  - 'administer access token entities'
  - 'administer account settings'
  - 'administer blocks'
  - 'administer comment display'
  - 'administer comment fields'
  - 'administer comment form display'
  - 'administer comment types'
  - 'administer comments'
  - 'administer configuration split'
  - 'administer content types'
  - 'administer device tokens'
  - 'administer display modes'
  - 'administer filters'
  - 'administer languages'
  - 'administer menu'
  - 'administer modules'
  - 'administer node display'
  - 'administer node fields'
  - 'administer node form display'
  - 'administer nodes'
  - 'administer permissions'
  - 'administer push notification'
  - 'administer rest resources'
  - 'administer rules'
  - 'administer rules components'
  - 'administer rules reactions'
  - 'administer search'
  - 'administer shortcuts'
  - 'administer simple_oauth entities'
  - 'administer site configuration'
  - 'administer software updates'
  - 'administer taxonomy'
  - 'administer taxonomy_term display'
  - 'administer taxonomy_term fields'
  - 'administer taxonomy_term form display'
  - 'administer themes'
  - 'administer url aliases'
  - 'administer user display'
  - 'administer user fields'
  - 'administer user form display'
  - 'administer users'
  - 'administer views'
  - 'bypass node access'
  - 'bypass rules access'
  - 'cancel account'
  - 'change own username'
  - 'create device token'
  - 'create incident content'
  - 'create url aliases'
  - 'customize shortcut links'
  - 'delete all revisions'
  - 'delete any incident content'
  - 'delete configuration'
  - 'delete device tokens'
  - 'delete incident revisions'
  - 'delete own access token entities'
  - 'delete own incident content'
  - 'delete own simple_oauth entities'
  - 'delete push notifications'
  - 'delete terms in berichttypen'
  - 'edit any incident content'
  - 'edit own access token entities'
  - 'edit own comments'
  - 'edit own incident content'
  - 'edit push notifications'
  - 'edit terms in berichttypen'
  - 'execute php code'
  - 'export configuration'
  - 'grant content access'
  - 'grant own content access'
  - 'grant simple_oauth codes'
  - 'import configuration'
  - 'link to any page'
  - 'manage services'
  - 'post comments'
  - 'refresh access token'
  - 'restful delete nicol_push_notifications'
  - 'restful get nicol_messagetypes'
  - 'restful get nicol_messagetypes_anon'
  - 'restful post nicol_incidents'
  - 'restful post nicol_incidents_anonymous'
  - 'restful post nicol_push_notifications'
  - 'revert all revisions'
  - 'revert configuration'
  - 'revert incident revisions'
  - 'search content'
  - 'select account cancellation method'
  - 'send push notifications'
  - 'services update form display access'
  - 'services view form display access'
  - 'show term permission form on term page'
  - 'skip comment approval'
  - 'switch shortcut sets'
  - 'switch users'
  - 'synchronize configuration'
  - 'translate interface'
  - 'update own simple_oauth entities'
  - 'use advanced search'
  - 'view all revisions'
  - 'view config updates report'
  - 'view device tokens'
  - 'view incident revisions'
  - 'view own access token entities'
  - 'view own simple_oauth entities'
  - 'view own unpublished content'
  - 'view push notifications'
  - 'view the administration theme'
