# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

registration: with-pass
register_subject: 'Activatielink voor de e-OvB EZOEF-app'
register_body: "Geachte collega,\r\n\r\nIemand heeft uw mailadres opgegeven voor registratie van de e-OvB EZOEF-app op een mobiel apparaat.\r\nAls dit inderdaad door u is gedaan en u wilt de app activeren op uw mobiele apparaat, klik dan op onderstaande link, of kopieer deze naar uw internetbrowser.\r\nAls dit niet door u is gedaan, stuur deze e-mail dan door naar contact@e-overheidvoorbedrijven.nl.\r\n\r\nActivatielink:\r\n[user:registrationpassword-url]\r\n\r\nDeze link kan slechts 1 keer gebruikt worden.\r\n\r\ne-OvB Beheer"
registration_ftll_expire: true
registration_ftll_timeout: 86400
_core:
  default_config_hash: BQQ8tRXH3JBDK2r_7fQOtVBSRxOJDS6POPpSZdW7fFk
langcode: nl
