# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 3929a2bf-abfa-4aed-8eea-f2808cd8577c
langcode: nl
status: true
dependencies: {  }
_core:
  default_config_hash: j5zLMOdJBqC0bMvSdth5UebkprJB8g_2FXHqhfpJzow
id: anonymous
label: 'Anonieme gebruiker'
weight: 0
is_admin: false
permissions:
  - 'access content'
  - 'restful post nicol_registration'
  - 'use text format real_plain_text'
