# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: c73846c0-644f-4fe3-aee6-a60fe20bafd2
langcode: nl
status: true
dependencies: {  }
id: verstoring_berichtenbox
label: 'Verstoring Berichtenbox'
description: ''
body:
  value: "<p>Verstoring Berichtenbox</p>\r\n\r\n<p>Als gevolg van een storing is de Berichtenbox niet beschikbaar ['via e-Herkenning. Via AVB-account kan wel op de Berichtenbox worden ingelogd']. Onderzocht wordt wat de oorzaak is.</p>\r\n"
  format: wysiwyg_default
weight: null
node_types: {  }
