# Copyright 2023 De Staat der Nederlanden, Dienst ICT Uitvoering
# SPDX-License-Identifier: EUPL-1.2

uuid: 6d2e392b-31ce-4cdb-8c62-ae43b4f71896
langcode: nl
status: true
dependencies: {  }
id: tvs_verstoring_digid
label: 'TVS Verstoring DigiD'
description: ''
body:
  value: "<p>TVS Verstoring DigiD</p>\r\n\r\n<p>Op dit moment is er een storing met DigiD via TVS op de [productie/acceptatie]-omgeving. Onderzocht wordt wat de oorzaak is.</p>\r\n"
  format: wysiwyg_default
weight: null
node_types: {  }
